### ISSUE TITLE
error in build

### ISSUE THREAD

**Issue by michaelkuty** [or/jeeves#11]
[2015-09-17 12:17:26,548: ERROR/MainProcess] Task jeeves.core.service.start_build[0527a4ae-d61a-46d4-92c5-b8eac2cb8723] raised unexpected: IndexError('tuple index out of range',)
	Traceback (most recent call last):
	  File "/srv/leonardo/sites/jeeves/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
	    R = retval = fun(*args, **kwargs)
	  File "/srv/leonardo/sites/jeeves/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
	    return self.run(*args, **kwargs)
	  File "/srv/leonardo/sites/jeeves/jeeves/jeeves/core/service.py", line 115, in start_build
	    script = script.format(**script_context)
	IndexError: tuple index out of range

i don't know what I doing wrong

**Comment by or** [comment]
Can you post your build script? The code there simply uses `.format()`, so it isn't very robust if the script contains dodgy placeholders.

I'm assuming there's something like this: `{foo[1]}` in there.

**Comment by michaelkuty** [comment]
i just paste you example

	#!/usr/bin/env python
	import sys
	import time
	from datetime import datetime

	print("{} did some things...".format(datetime.now()))
	time.sleep(2)
	print("{} did some more things...".format(datetime.now()))
	time.sleep(3)

	for i in range(150):
	    print("line {}".format(i))
	    sys.stdout.flush()
	    time.sleep(0.1)

	print("all done!")

btw: a maked some contribs to @mbertheau branch which has PR #9

**Comment by or** [comment]
Ah, right. That script belongs in something like `build.py` and the script in the project just calls it by `./build.py`.

But maybe you have an old version, too. The code is changing quite a bit right now, because it's still a very young project. :)

**Comment by michaelkuty** [comment]
uuf, that happens when ``format`` formats the script where i had ``{}`` this needs tuple of arguments
you can't use this format code in your script, o didn't know that script must be a shell script

**Comment by mbertheau** [comment]
Good point here. The UI should make it clear that a shell script is expected.
